services:
  frontend:
    container_name: frontend
    build:
      context: student-form-app/
    image: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - my-network
  backend:
    container_name: backend
    build:
      context: Backend/
    image: backend
    ports:
      - "3500:3500"
    env_file:
      - Backend/.env
    depends_on:
      - db
    networks:
      - my-network
  db:
    container_name: mysql-Container
    build:
      context: .
    image: mysql-studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql-data:
networks:
  my-network:
    driver: bridge
